In [1]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3]) # 1x3 matrix
a2 = np.array([[2,3,4],[4,5,6],[5,6,7]]) # 3x3 matrix
a2.diagonal()

array([2, 5, 7])

### Special Arrays

In [10]:
zeros = np.zeros([3,3]) # 3x3 zero matrix
ones = np.ones([1,3]) # 1x3 one matrix
identity = np.eye(3) # 3x3 identity matrix


In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones

array([[1., 1., 1.]])

In [13]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Operations

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr+10) # add 10 to each element
print(arr*2) # multiply each element by 2
print(arr**2) # square each element

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
