In [1]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3]) # 1x3 matrix
a2 = np.array([[2,3,4],[4,5,6],[5,6,7]]) # 3x3 matrix
a2.diagonal()

array([2, 5, 7])

### Special Arrays

In [10]:
zeros = np.zeros([3,3]) # 3x3 zero matrix
ones = np.ones([1,3]) # 1x3 one matrix
identity = np.eye(3) # 3x3 identity matrix


In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones

array([[1., 1., 1.]])

In [13]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Operations

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr+10) # add 10 to each element
print(arr*2) # multiply each element by 2
print(arr**2) # square each element

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print(a1+a2) # adding 2 matrices
print(np.dot(a1, a2)) # Dot product

[[ 3  5  7]
 [ 5  7  9]
 [ 6  8 10]]
[25 31 37]


In [ ]:
print(np.mean(a1)) # mean of all elements
print(np.std(a1)) # standard deviation of all elements
print(np.max(a2)) # max value of the matrix
print(np.argmax(a1)) # maximum number of arguemnts in a matrix

2.0
0.816496580927726
7
2


### Array Indexing and Slicing

In [33]:
arr = np.array([[1,2,3], [33,44,55], [2,1,1]])

print(arr[0,1]) # get the element that is in the first row and second column
print(arr[:,1]) # all rows, second column
print(arr[arr > 5]) # row containing elements greater than 5

2
[ 2 44  1]
[33 44 55]
